name: formatted_text
description: >
  A simple text formatting package.
  Use to format text in TextField and Text widgets
version: 3.1.0
homepage: https://github.com/NirmalAriyathilake/formatted_text

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter

flutter: null
