name: formatted_text
description: >
  A simple text formatting package.
  Use to format text in TextField and Text widgets
version: 2.0.0
homepage: https://github.com/NirmalAriyathilake/formatted_text

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter: null
